name: antisepticks
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"



dependencies:
  flutter:
    sdk: flutter

  sqflite: ^1.3.0
  path_provider: ^1.6.7
  path: ^1.6.4 #not update, conflict with another dependency
  cupertino_icons: ^0.1.3
  dio: ^3.0.9
  flutter_bloc: ^4.0.0
  equatable: ^1.1.1
  data_connection_checker: ^0.3.4
  get_it: ^4.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

